# Generated by Django 5.2.10 on 2026-01-27 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('cedula', models.CharField(max_length=10, unique=True, verbose_name='Cédula')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('grupo', models.IntegerField(choices=[(1, 'Grupo 1'), (2, 'Grupo 2'), (3, 'Grupo 3'), (4, 'Grupo 4')], verbose_name='Grupo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('visible_en_registro', models.BooleanField(default=True, verbose_name='Visible en Registro')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden de visualización')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lider_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Sistema')),
            ],
            options={
                'verbose_name': 'Líder',
                'verbose_name_plural': 'Líderes',
                'ordering': ['grupo', 'orden', 'nombre_completo'],
            },
        ),
    ]
