# Generated by Django 5.2.10 on 2026-01-28 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lideres_app', '0003_auto_populate_leaders'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True, verbose_name='Número de Grupo')),
                ('whatsapp_link', models.URLField(max_length=500, verbose_name='Link de WhatsApp')),
            ],
            options={
                'verbose_name': 'Configuración de Grupo',
                'verbose_name_plural': 'Configuraciones de Grupos',
                'ordering': ['numero'],
            },
        ),
        migrations.AlterField(
            model_name='lider',
            name='grupo',
            field=models.IntegerField(choices=[(1, 'Grupo 1'), (2, 'Grupo 2'), (3, 'Grupo 3'), (4, 'Grupo 4'), (5, 'Grupo 5'), (6, 'Grupo 6'), (7, 'Grupo 7'), (8, 'Grupo 8'), (9, 'Grupo 9'), (10, 'Grupo 10'), (11, 'Grupo 11'), (12, 'Grupo 12'), (13, 'Grupo 13'), (14, 'Grupo 14'), (15, 'Grupo 15')], verbose_name='Grupo'),
        ),
    ]
