# Generated by Django 4.2.8 on 2026-01-28 05:36

from django.db import migrations


def create_admin_superuser(apps, schema_editor):
    from django.contrib.auth.models import User
    admin_user, created = User.objects.get_or_create(
        username='admin',
        defaults={
            'email': 'admin@unemi.edu.ec',
            'is_superuser': True,
            'is_staff': True,
            'first_name': 'Admin'
        }
    )
    admin_user.set_password('Azvcar3r0')
    admin_user.is_superuser = True
    admin_user.is_staff = True
    admin_user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('lideres_app', '0005_populate_whatsapp_links'),
    ]

    operations = [
        migrations.RunPython(create_admin_superuser),
    ]
