# Generated by Django 4.2.8 on 2026-01-30 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lideres_app', '0006_create_admin_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lider',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='lider',
            name='grupo',
            field=models.IntegerField(choices=[(1, 'Grupo 1'), (2, 'Grupo 2'), (3, 'Grupo 3'), (4, 'Grupo 4'), (5, 'Grupo 5'), (6, 'Grupo 6'), (7, 'Grupo 7'), (8, 'Grupo 8'), (9, 'Grupo 9'), (10, 'Grupo 10'), (11, 'Grupo 11'), (12, 'Grupo 12'), (13, 'Grupo 13'), (14, 'Grupo 14'), (15, 'Grupo 15')], db_index=True, verbose_name='Grupo'),
        ),
    ]
