# Generated by Django 4.2.8 on 2026-02-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lideres_app', '0011_auto_redistribute_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEscaneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase_actual', models.CharField(choices=[('CERRADO', 'Escaneo Cerrado'), ('INICIO', 'Registro de Inicio'), ('FIN', 'Registro de Fin')], default='CERRADO', max_length=15, verbose_name='Fase Actual del Proceso')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Escaneo',
                'verbose_name_plural': 'Configuraciones de Escaneo',
            },
        ),
    ]
