# Generated by Django 4.2.8 on 2026-02-08 18:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCertificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_certificado', models.CharField(default='CERTIFICADO DE PARTICIPACIÓN', max_length=200, verbose_name='Título del Certificado')),
                ('subtitulo', models.CharField(default='Marcha por los 25 Años de UNEMI', max_length=300, verbose_name='Subtítulo')),
                ('texto_cuerpo', models.TextField(default='Se certifica que {nombre} participó en la Marcha conmemorativa por los 25 años de vida institucional de la Universidad Estatal de Milagro, realizada el 8 de febrero de 2026.', help_text='Usa {nombre} como placeholder para el nombre del participante', verbose_name='Texto del Certificado')),
                ('firma_1_imagen', models.ImageField(blank=True, null=True, upload_to='certificados/firmas/', verbose_name='Firma 1 (PNG)')),
                ('firma_1_nombre', models.CharField(blank=True, default='', max_length=150, verbose_name='Nombre Firmante 1')),
                ('firma_1_cargo', models.CharField(blank=True, default='', max_length=150, verbose_name='Cargo Firmante 1')),
                ('firma_2_imagen', models.ImageField(blank=True, null=True, upload_to='certificados/firmas/', verbose_name='Firma 2 (PNG)')),
                ('firma_2_nombre', models.CharField(blank=True, default='', max_length=150, verbose_name='Nombre Firmante 2')),
                ('firma_2_cargo', models.CharField(blank=True, default='', max_length=150, verbose_name='Cargo Firmante 2')),
                ('color_primario', models.CharField(default='#0F1E4B', max_length=7, validators=[django.core.validators.RegexValidator(message='El color debe ser formato hexadecimal (#RRGGBB)', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Color Primario (Azul UNEMI)')),
                ('color_secundario', models.CharField(default='#EF7D00', max_length=7, validators=[django.core.validators.RegexValidator(message='El color debe ser formato hexadecimal (#RRGGBB)', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Color Secundario (Naranja UNEMI)')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Certificado',
                'verbose_name_plural': 'Configuración de Certificados',
            },
        ),
    ]
