# Generated by Django 4.2.8 on 2026-02-09 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncertificado',
            name='firma_3_cargo',
            field=models.CharField(blank=True, default='COORDINADORA', max_length=150, verbose_name='Cargo Firmante 3'),
        ),
        migrations.AddField(
            model_name='configuracioncertificado',
            name='firma_3_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='certificados/firmas/', verbose_name='Firma 3 (Derecha - R. Jurado)'),
        ),
        migrations.AddField(
            model_name='configuracioncertificado',
            name='firma_3_nombre',
            field=models.CharField(blank=True, default='Roxana Jurado', max_length=150, verbose_name='Nombre Firmante 3'),
        ),
        migrations.AddField(
            model_name='configuracioncertificado',
            name='logo_centro',
            field=models.ImageField(blank=True, null=True, upload_to='certificados/logos/', verbose_name='Logo Centro (25 Años)'),
        ),
        migrations.AddField(
            model_name='configuracioncertificado',
            name='logo_derecha',
            field=models.ImageField(blank=True, null=True, upload_to='certificados/logos/', verbose_name='Logo Derecha (FEUE)'),
        ),
        migrations.AddField(
            model_name='configuracioncertificado',
            name='logo_izquierda',
            field=models.ImageField(blank=True, null=True, upload_to='certificados/logos/', verbose_name='Logo Izquierda (MUC)'),
        ),
        migrations.AlterField(
            model_name='configuracioncertificado',
            name='firma_1_cargo',
            field=models.CharField(blank=True, default='DIRECTORA DE MARCHA', max_length=150, verbose_name='Cargo Firmante 1'),
        ),
        migrations.AlterField(
            model_name='configuracioncertificado',
            name='firma_1_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='certificados/firmas/', verbose_name='Firma 1 (Izquierda - P. Palacios)'),
        ),
        migrations.AlterField(
            model_name='configuracioncertificado',
            name='firma_1_nombre',
            field=models.CharField(blank=True, default='Paola Palacios', max_length=150, verbose_name='Nombre Firmante 1'),
        ),
        migrations.AlterField(
            model_name='configuracioncertificado',
            name='firma_2_cargo',
            field=models.CharField(blank=True, default='RECTOR UNEMI', max_length=150, verbose_name='Cargo Firmante 2'),
        ),
        migrations.AlterField(
            model_name='configuracioncertificado',
            name='firma_2_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='certificados/firmas/', verbose_name='Firma 2 (Centro - Rector)'),
        ),
        migrations.AlterField(
            model_name='configuracioncertificado',
            name='firma_2_nombre',
            field=models.CharField(blank=True, default='Fabricio Guevara Viejó', max_length=150, verbose_name='Nombre Firmante 2'),
        ),
    ]
