# Generated by Django 4.2.8 on 2026-02-09 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_configuracioncertificado_firma_3_cargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncertificado',
            name='mensaje_lideres_cuerpo',
            field=models.TextField(default='Gracias por tu apoyo y esfuerzo por ser parte de esta lucha y hacer que todo salga bien.', verbose_name='Cuerpo Mensaje Líderes'),
        ),
        migrations.AddField(
            model_name='configuracioncertificado',
            name='mensaje_lideres_titulo',
            field=models.CharField(default='¡Gracias por tu Liderazgo!', max_length=200, verbose_name='Título Mensaje Líderes'),
        ),
    ]
