# Generated by Django 4.2.8 on 2026-02-09 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_configuracioncertificado_mensaje_lideres_cuerpo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncertificado',
            name='texto_certificado_lideres',
            field=models.TextField(default='Se certifica que {nombre} participó como LÍDER del GIRO {grupo} en la Marcha conmemorativa por los 25 años de vida institucional de la Universidad Estatal de Milagro.', help_text='Usa {nombre} y {grupo} como placeholders.', verbose_name='Texto Certificado Líderes'),
        ),
    ]
