# Generated by Django 4.2.8 on 2026-02-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_configuracioncertificado_texto_certificado_lideres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracioncertificado',
            name='firma_1_imagen',
            field=models.TextField(blank=True, null=True, verbose_name='Firma 1 (Base64) - No editar manualmente'),
        ),
        migrations.AlterField(
            model_name='configuracioncertificado',
            name='firma_2_imagen',
            field=models.TextField(blank=True, null=True, verbose_name='Firma 2 (Base64) - No editar manualmente'),
        ),
        migrations.AlterField(
            model_name='configuracioncertificado',
            name='firma_3_imagen',
            field=models.TextField(blank=True, null=True, verbose_name='Firma 3 (Base64) - No editar manualmente'),
        ),
    ]
