# Generated by Django 4.2.8 on 2026-02-11 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_configuracioncertificado_firma_1_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracioncertificado',
            name='firma_1_cargo',
            field=models.CharField(blank=True, default='RECTOR', max_length=150, verbose_name='Cargo Firmante 1'),
        ),
        migrations.AlterField(
            model_name='configuracioncertificado',
            name='firma_1_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='certificados/firmas/', verbose_name='Firma 1 (Rector) - Subir PNG con fondo transparente'),
        ),
        migrations.AlterField(
            model_name='configuracioncertificado',
            name='firma_1_nombre',
            field=models.CharField(blank=True, default='PhD. Fabricio Guevara Viejó', max_length=150, verbose_name='Nombre Firmante 1'),
        ),
        migrations.AlterField(
            model_name='configuracioncertificado',
            name='firma_2_cargo',
            field=models.CharField(blank=True, default='REPRESENTANTE OCS\nPRESIDENTE MUC', max_length=150, verbose_name='Cargo Firmante 2'),
        ),
        migrations.AlterField(
            model_name='configuracioncertificado',
            name='firma_2_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='certificados/firmas/', verbose_name='Firma 2 (MUC) - Subir PNG con fondo transparente'),
        ),
        migrations.AlterField(
            model_name='configuracioncertificado',
            name='firma_2_nombre',
            field=models.CharField(blank=True, default='Paola Palacios P.', max_length=150, verbose_name='Nombre Firmante 2'),
        ),
        migrations.AlterField(
            model_name='configuracioncertificado',
            name='firma_3_cargo',
            field=models.CharField(blank=True, default='PRESIDENTE FEUE', max_length=150, verbose_name='Cargo Firmante 3'),
        ),
        migrations.AlterField(
            model_name='configuracioncertificado',
            name='firma_3_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='certificados/firmas/', verbose_name='Firma 3 (FEUE) - Subir PNG con fondo transparente'),
        ),
        migrations.AlterField(
            model_name='configuracioncertificado',
            name='firma_3_nombre',
            field=models.CharField(blank=True, default='Roxana Jurado A.', max_length=150, verbose_name='Nombre Firmante 3'),
        ),
    ]
