# Generated by Django 4.2.8 on 2026-02-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_configuracioncertificado_firma_1_cargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracioncertificado',
            name='texto_cuerpo',
            field=models.TextField(default='Por haber participado en la Marcha por la Excelencia, evidenciando liderazgo, compromiso y una actitud proactiva en favor del crecimiento, la calidad y los valores que fortalecen nuestra alma mater.', help_text='Usa {nombre} como placeholder para el nombre del participante', verbose_name='Texto del Certificado'),
        ),
    ]
