# Generated by Django 5.2.10 on 2026-01-27 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lideres_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('cedula', models.CharField(max_length=10, unique=True, verbose_name='Cédula')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('modalidad', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('EN_LINEA', 'En Línea'), ('SEMIPRESENCIAL', 'Semipresencial')], max_length=20, verbose_name='Modalidad')),
                ('facultad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Facultad')),
                ('carrera', models.CharField(max_length=150, verbose_name='Carrera')),
                ('codigo_qr', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Código QR')),
                ('asistio', models.BooleanField(default=False, verbose_name='Asistió')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_asistencia', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Asistencia')),
                ('registrado_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Registrado por')),
                ('grupo', models.IntegerField(verbose_name='Grupo asignado (Heredado)')),
                ('lider_invitador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alumnos', to='lideres_app.lider', verbose_name='Líder que lo invitó')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titular_nombre', models.CharField(max_length=150, verbose_name='Nombre del Titular')),
                ('titular_cedula', models.CharField(max_length=10, verbose_name='Cédula del Titular')),
                ('banco', models.CharField(choices=[('PACIFICO', 'Banco Pacífico'), ('PICHINCHA', 'Banco Pichincha'), ('GUAYAQUIL', 'Banco Guayaquil')], max_length=100, verbose_name='Banco')),
                ('tipo_cuenta', models.CharField(choices=[('AHORROS', 'Ahorros'), ('CORRIENTE', 'Corriente')], max_length=20, verbose_name='Tipo de Cuenta')),
                ('numero_cuenta', models.CharField(max_length=30, verbose_name='Número de Cuenta')),
                ('es_propia', models.BooleanField(default=True, verbose_name='Es cuenta propia')),
                ('alumno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_bancaria', to='alumnos.alumno', verbose_name='Alumno')),
            ],
            options={
                'verbose_name': 'Cuenta Bancaria',
                'verbose_name_plural': 'Cuentas Bancarias',
            },
        ),
    ]
