# Generated by Django 4.2.8 on 2026-01-28 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lideres_app', '0005_populate_whatsapp_links'),
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='lider_invitador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='lideres_app.lider', verbose_name='Líder que lo invitó'),
        ),
    ]
