# Generated by Django 4.2.8 on 2026-01-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_alter_alumno_lider_invitador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='carrera',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Carrera'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='modalidad',
            field=models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('EN_LINEA', 'En Línea'), ('SEMIPRESENCIAL', 'Semipresencial'), ('EGRESADO', 'Egresado')], max_length=20, verbose_name='Modalidad'),
        ),
    ]
