# Generated by Django 5.0.1 on 2026-01-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_alter_alumno_carrera_alter_alumno_modalidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='es_externo',
            field=models.BooleanField(default=False, verbose_name='¿Es externo a UNEMI?'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='modalidad',
            field=models.CharField(blank=True, choices=[('PRESENCIAL', 'Presencial'), ('EN_LINEA', 'En Línea'), ('SEMIPRESENCIAL', 'Semipresencial'), ('EGRESADO', 'Egresado')], max_length=20, null=True, verbose_name='Modalidad'),
        ),
    ]
