# Generated by Django 5.0.1 on 2026-01-29 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0004_alumno_es_externo_alter_alumno_modalidad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CuentaBancaria',
        ),
    ]
