# Generated by Django 5.0.1 on 2026-01-29 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0005_delete_cuentabancaria'),
        ('lideres_app', '0006_create_admin_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='grupo',
            field=models.IntegerField(default=0, verbose_name='Grupo asignado (Heredado)'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='lider_invitador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumnos', to='lideres_app.lider', verbose_name='Líder que lo invitó'),
        ),
    ]
