# Generated by Django 4.2.8 on 2026-01-30 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0006_alter_alumno_grupo_alter_alumno_lider_invitador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='asistio',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Asistió'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='grupo',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Grupo asignado (Heredado)'),
        ),
    ]
