# Generated by Django 4.2.8 on 2026-02-01 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0007_alter_alumno_asistio_alter_alumno_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='modalidad',
            field=models.CharField(blank=True, choices=[('PRESENCIAL', 'Presencial'), ('EN_LINEA', 'En Línea'), ('SEMIPRESENCIAL', 'Semipresencial'), ('EGRESADO', 'Egresado'), ('POSGRADO', 'Posgrado')], max_length=20, null=True, verbose_name='Modalidad'),
        ),
    ]
