# Generated by Django 4.2.8 on 2026-02-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0008_alter_alumno_modalidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha/Hora de Fin'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha/Hora de Inicio'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='ha_finalizado',
            field=models.BooleanField(db_index=True, default=False, verbose_name='¿Finalizó Marcha?'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='ha_iniciado',
            field=models.BooleanField(db_index=True, default=False, verbose_name='¿Inició Marcha?'),
        ),
    ]
