# Generated by Django 4.2.8 on 2026-02-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0009_alumno_fecha_fin_alumno_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='certificado_entregado',
            field=models.BooleanField(db_index=True, default=False, verbose_name='¿Certificado Entregado?'),
        ),
    ]
