# Generated by Django 4.2.8 on 2026-02-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0010_alumno_certificado_entregado'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='fecha_entrega_certificado',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Entrega del Certificado'),
        ),
    ]
