# Generated by Django 4.2.8 on 2026-02-06 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0009_alumno_fecha_fin_alumno_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipanteSorteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('cedula', models.CharField(max_length=10, verbose_name='Cédula')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('fecha_copiado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo para Sorteos')),
                ('alumno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='participante_sorteo', to='alumnos.alumno')),
            ],
            options={
                'verbose_name': 'Participante de Sorteo',
                'verbose_name_plural': 'Participantes de Sorteo',
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='Ganador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_sorteo', models.CharField(choices=[('PREMIO', 'Premio Regular'), ('IPHONE', 'iPhone')], db_index=True, max_length=10, verbose_name='Tipo de Sorteo')),
                ('numero_premio', models.IntegerField(verbose_name='Número de Premio')),
                ('descripcion_premio', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción del Premio')),
                ('fecha_sorteo', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Sorteo')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='premios_ganados', to='sorteos.participantesorteo')),
            ],
            options={
                'verbose_name': 'Ganador',
                'verbose_name_plural': 'Ganadores',
                'ordering': ['tipo_sorteo', 'numero_premio'],
                'unique_together': {('tipo_sorteo', 'numero_premio')},
            },
        ),
    ]
